name: Build and Test

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [
                    windows-latest,
                    ubuntu-latest,
                  # latest available X86_64 target
                    macos-12,
                  # latest is ARM
                    macos-latest,
                ]
        steps:
            -   uses: actions/checkout@v2  # Checkout the repository

            -   uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: '21'

            -   name: Build with Gradle
                run: ./gradlew build --no-daemon

            -   name: Run tests
                run: ./gradlew test --no-daemon

            # create installer
            -   name: Package
                run: ./gradlew jpackage --no-daemon

            # Required to preserve permissions; otherwise many of the packages will not work!
            # See https://github.com/actions/upload-artifact#maintaining-file-permissions-and-case-sensitive-files
            -   name: Tar packages
                run: tar -cvf build-artifacts-${{ matrix.os }}.tar build/jpackage

            -   name: Archive build artifacts
                # Only runs if the previous steps were successful
                if: success()
                uses: actions/upload-artifact@v4
                with:
                    name: build-artifacts-${{ matrix.os }}
                    path: build-artifacts-${{ matrix.os }}.tar
